#!/bin/bash/

# Assumes git has already been installed and the ubuntu-config repository
# clones and placed in ~/files/repos/ubuntu-config/

sudo apt-get remove indicator-messages
sudo apt-get purge firefox thunderbird

sudo apt update
sudo apt upgrade

sudo apt-get install vim tmux build-essential texlive-full inotify-tools chromium-browser


sudo sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop

xdg-user-dirs-update --set DESKTOP ~/downloads
xdg-user-dirs-update --set DOWNLOAD ~/downloads
xdg-user-dirs-update --set TEMPLATES ~/downloads
xdg-user-dirs-update --set PUBLICSHARE ~/downloads
xdg-user-dirs-update --set DOCUMENTS ~/downloads
xdg-user-dirs-update --set MUSIC ~/downloads
xdg-user-dirs-update --set PICTURES ~/downloads
xdg-user-dirs-update --set VIDEOS ~/downloads

mkdir -p ~/bin ~/downloads ~/files

sudo sed -i s/enabled=True/enabled=False/g /etc/xdg/user-dirs.conf


rm -f ~/.bashrc
rm -f ~/.bash_aliases
rm -f ~/.vimrc
rm -f ~/.vimrc.line-feeder-3
rm -f ~/.gitconfig
rm -f ~/.gitignore_global
rm -f ~/.tmux.conf

DIR=/home/mickey/files/repos/ubuntu-config
ln -s $DIR/bashrc ~/.bashrc
ln -s $DIR/bash_aliases ~/.bash_aliases
ln -s $DIR/vimrc ~/.vimrc
ln -s $DIR/vimrc.line-feeder-3 ~/.vimrc.line-feeder-3
ln -s $DIR/gitconfig ~/.gitconfig
ln -s $DIR/gitignore_global ~/.gitignore_global
ln -s $DIR/tmux.conf ~/.tmux.conf

git clone git@github.com:mickwar/binaries ~/files/repos/binaries 
git clone git@github.com:mickwar/binaries ~/files/repos/binaries 
