#!/bin/bash/

cd $HOME

# Assumes git has already been installed and the ubuntu-config repository
# clones and placed in ~/files/repos/ubuntu-config/

sudo apt-get remove indicator-messages
sudo apt-get purge firefox thunderbird

sudo apt update
sudo apt upgrade


### Install some standard packages
sudo apt-get install vim tmux build-essential texlive-full inotify-tools

### Install Chrome
sudo apt-get install libxss1 libappindicator1 libindicator7
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome*.deb
sudo apt-get install -f
sudo dpkg -i google-chrome*.deb
rm -f google-chrome-stable_current_amd64.deb
sudo update-alternatives --config google-chrome

### Install R
echo "deb http://cran.cnr.berkeley.edu/bin/linux/ubuntu xenial/" | sudo tee -a  /etc/apt/sources.list

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo apt-get update
sudo apt-get install r-base

### Clean up home directory
sudo sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop

xdg-user-dirs-update --set DESKTOP ~/downloads
xdg-user-dirs-update --set DOWNLOAD ~/downloads
xdg-user-dirs-update --set TEMPLATES ~/downloads
xdg-user-dirs-update --set PUBLICSHARE ~/downloads
xdg-user-dirs-update --set DOCUMENTS ~/downloads
xdg-user-dirs-update --set MUSIC ~/downloads
xdg-user-dirs-update --set PICTURES ~/downloads
xdg-user-dirs-update --set VIDEOS ~/downloads

mkdir -p ~/bin ~/downloads ~/files

sudo sed -i s/enabled=True/enabled=False/g /etc/xdg/user-dirs.conf

rm -f ~/.bashrc
rm -f ~/.bash_aliases
rm -f ~/.vimrc
rm -f ~/.vimrc.line-feeder-3
rm -f ~/.gitconfig
rm -f ~/.gitignore_global
rm -f ~/.tmux.conf

DIR=/home/mickey/files/repos/ubuntu-config
ln -s $DIR/bashrc ~/.bashrc
ln -s $DIR/bash_aliases ~/.bash_aliases
ln -s $DIR/vimrc ~/.vimrc
ln -s $DIR/vimrc.line-feeder-3 ~/.vimrc.line-feeder-3
ln -s $DIR/gitconfig ~/.gitconfig
ln -s $DIR/gitignore_global ~/.gitignore_global
ln -s $DIR/tmux.conf ~/.tmux.conf

git clone git@github.com:mickwar/binaries ~/files/repos/binaries 
# git clone git@github.com:mickwar/data ~/files/repos/data
# git clone git@github.com:mickwar/homework ~/files/repos/homework

### Set custom datetime format
gsettings set com.canonical.indicator.datetime time-format 'custom'
gsettings set com.canonical.indicator.datetime custom-time-format '          %A     %d %b %Y     %H:%M:%S          '

### Mouse/touchpad settings
gsettings set org.gnome.desktop.peripherals.touchpad send-events 'disabled'
gsettings set org.gnome.desktop.peripherals.mouse speed 0.5
gsettings set org.gnome.desktop.peripherals.mouse natural-scroll false
gsettings set org.gnome.settings-daemon.peripherals.mouse double-click 300

### Keyboard settings
gsettings set org.gnome.desktop.peripherals.keyboard repeat true
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 20
gsettings set org.gnome.desktop.peripherals.keyboard delay 200

### Change background (to black)
gsettings set org.gnome.settings-daemon.plugins.background active true
gsettings set org.gnome.desktop.background picture-uri ''
gsettings set org.gnome.desktop.background picture-options 'none'
gsettings set org.gnome.desktop.background primary-color '#000000000000'
gsettings set org.gnome.desktop.background color-shading-type 'solid'
# The above lines weren't working in 14.04, follow up with these two lines
# gsettings set org.gnome.desktop.background secondary-color '#000000000000'
# gsettings set org.gnome.desktop.background color-shading-type 'vertical'

### Changing log-in screen background (to black)
sudo bash -c "cat << EOF > /usr/share/glib-2.0/schemas/10_unity_greeter_background.gschema.override
[com.canonical.unity-greeter]
background=''
background-color='#000000'
draw-grid=false
draw-user-backgrounds=false
EOF"
sudo glib-compile-schemas /usr/share/glib-2.0/schemas

